spring:
  application:
    name: microservice-study-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
microservice-study-service:
  greeting: "Que passa!"
  default-value: "Passa nadia"