spring:
  application:
    name: microservice-study-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
microservice-study-service:
  greeting: "Hello"
  default-value: "Default"